#define breche break
#define fall case
#define buchstabe char
#define konstante const
#define konstanter const
#define konstantes const
#define weiter continue
#define normal default
#define normalerweise default
#define tue do
#define doppel double
#define doppelt double
#define doppelte double
#define doppelter double
#define doppeltes double
#define ansonsten else
#define sonst else
#define aufzaehlung enum
#define auswaertig extern
#define auswaertige extern
#define auswaertiger extern
#define auswaertiges extern
#define schwebe float
#define fuer for
#define gehezu goto
#define falls if
#define eingereiht inline
#define eingereihte inline
#define eingereihter inline
#define eingereihtes inline
#define ganzzahl int
#define lang long
#define lange long
#define langer long
#define langes long
#define gross long
#define grosse long
#define grosser long
#define grosses long
#define einschaenk restrict
#define eingeschraenkt restrict
#define eingeschraenkte restrict
#define eingeschraenkter restrict
#define eingeschraenktes restrict
#define rueckkehr return
#define kurz short
#define kurze short
#define kurzer short
#define kurzes short
#define signiert signed
#define signierte signed
#define signierter signed
#define signiertes signed
#define groessevon sizeof
#define statisch static
#define statische static
#define statischer static
#define statisches static
#define struktur struct
#define schalter switch
#define schalte switch
#define typendefinition typedef
#define vereinigung union
#define unsigniert unsigned
#define unsignierte unsigned
#define unsignierter unsigned
#define unsigniertes unsigned
#define leere void
#define fluechtig volatile
#define fluechtige volatile
#define fluechtiger volatile
#define fluechtiges volatile
#define solange while

#define haupt main
#define wahr 1
#define falsch 0

#define druckf printf
#define atoz atoi
